Restricts cell identification ellipses to annotated regions
OxfordRSE/Electron-Sight pull request #47
Opened 2020-01-24 17:02 UTC by JABull1066

Only draws ellipses if ellipse centroid is inside annotated region. (Hopefully)

2020-01-24 17:12 UTC, martinjrobins requested changes
looks great, thanks @JABull1066, just need to tidy up the comments as per suggestions below

2020-01-24 17:12 UTC, martinjrobins commented on src/util/TileCellData.js
> +        // let shift_x = (this.tile.x) * this.tile.bounds.width;
don't think this is needed anymore?

2020-01-24 17:12 UTC, martinjrobins commented on src/util/TileCellData.js
> +        // test if ellipse centroid is contained in the annotation polygon
this comment doesn't refer to the line below, probably should be just above the `if` statement I think

2020-02-20 06:52 UTC, martinjrobins commented
hi @JABull1066, how are you going on this? Is it almost ready to merge?

2020-02-20 08:27 UTC, JABull1066 commented
Almost - I didn't quite manage to get everything done before getting pulled on to paper writing, unfortunately! I just need to find a free afternoon...could we add an extra day in to the week?

2020-02-28 16:31 UTC, martinjrobins approved these changes
great, thanks @JABull1066

2020-02-28 16:31 UTC, merged